name: t_app
description: Money transactions app, using flutter and bloc pattern, with sqlite database, and dio package for http requests.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  sqflite: ^2.0.2+1
  path_provider: ^2.0.10
  dio: ^4.0.6
  flutter_spinkit: ^5.2.0
  fluttertoast: ^8.0.9


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
